AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MoX:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./extractors
      Handler: mox.mox_extractor.lambda_mox
      Runtime: python3.11
      Timeout: 900  # Set timeout to 30 seconds (adjust as needed)
